### ISSUE TITLE
[ISSUE] The blue circle from the medic stays even after the medic dies

### ISSUE THREAD

**Issue by NFeruch** [KARPED1EM/TownOfHostEdited#122]
If I understand the medic role correctly, the blue circle shows which people are protected. After the medic dies, they aren't protected.

The issue is that the blue circle stays next to the peoples' names even after the medic dies. I feel like it should go away when they are no longer being protected

**Comment by Sand-and-Beans** [comment]
That's what I thought too =D

**Comment by Gurge44** [comment]
This was done so the shielded player doesn't know when the Medic is dead and also doesn't know when someone tried to kill them

**Comment by KARPED1EM** [comment]
no i think medic should protect players even they are died

**Comment by NFeruch** [comment]
@KARPED1EM that's what I think as well, the medic should protect players even after they die

**Comment by Gurge44** [comment]
I meant they know when the medic dies in the round. Like they know how long ago the kill was.
I guess only I'm hosting competitive lobbies where this matters

**Comment by NFeruch** [comment]
@Gurge44 what discord are you playing ranked tohe on?

**Comment by Gurge44** [comment]
And the reason why I don't like it when the protection still lasts when the Medic is dead, cause it's already annoying continuously not being able to kill a certain person. And if the Evil Guesser finds out who the medic is and guesses them, then that did nothing because the shield is still there??
Come on, at least make it a setting (eg. Medic shield breaks when the Medic dies: ON/OFF)

**Comment by KARPED1EM** [comment]
Additional options for some Medic are planned
