### ISSUE TITLE
Error in string.csv

### ISSUE THREAD

**Issue by Tommy-XL** [KARPED1EM/TownOfHostEdited#16]
The key "TabGroup.ImpostorRoles" is repeated 2 times and there is no key with "TabGroup.CrewmateRoles"

I would fix it myself, but I don't understand where the Chinese words come from with the key "TabGroup.CrewmateRoles" which is not in string.csv

![image](https://user-images.githubusercontent.com/104814436/218310671-b59cec1a-f67a-4bec-b76e-eb6b8f11dfa6.png)

**Comment by Tommy-XL** [comment]
Same with "TabGroup.Addons"

![image](https://user-images.githubusercontent.com/104814436/218310957-06df3897-4350-4864-8cb4-caac790f83f8.png)

**Comment by Tommy-XL** [comment]
Sorry, I looked at the source code, and everything turned out to be in order

**Comment by KARPED1EM** [comment]
Anyway, thanks for your issue
And, are you doing a ruassian translate for this fork? I'm really happy that someone can do this
But you need to change some code in [Translator.cs](https://github.com/KARPED1EM/TownOfHostEdited/blob/TOHE/Modules/Translator.cs) if you wanna add a new language.
Cause we have no ability to do any translate so that we deleted other languages

**Comment by Tommy-XL** [comment]
Oops, sorry, but I don't understand the C# code and have no idea how to change it, but I wanted to add English and Russian translation (I originally thought that all changes in string.csv would be applied in the mod and I didn't know that the code didn't supports languages)

**Comment by KARPED1EM** [comment]
Sorry we overlooked it, I just uploaded a commit to fix this
