### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Tommy-XL** [KARPED1EM/TownOfHostEdited#23]
While playing today with the mod, I found the bugs:

1. If someone reports a body during camouflage, then players without mods do not see nicknames (the Host sees all nicknames at the same time)

2. If you enable the setting so that it is impossible to report a body during camouflage, and at the same time someone will be killed during camouflage, and after the end of camouflage it will not be possible to report a dead body

3. If someone is killed during the game and the deceased player leaves the game, the Detective will not be able to report this body

4. Role Doctor sometimes does not see the causes of death, or sometimes he sees but not all causes of death

5. Evil Guesser and Nice Guesser "/bt" Command not working (If you enter everything correctly, then instead of guessing, it shows the instruction)

**Comment by KARPED1EM** [comment]
1 and 2 maybe we won't fix it.  Recently we have received a lot of bug feedback about camouflage.  For example, during camouflage, some players can enter forbidden vent, shapeshift are not restored when the meeting is start, and skills of warlocks and puppeteers become invalid, etc.  Some of these questions come from TOH and some from TOHE.  Instead of fixing a lot of camouflage bugs maybe we'll remove this option and make a camouflage skill impostor.

Then 3, do you mean the detective is unable to hold a meeting through the dead body, or is it unable to show the detective's clues that the detective does not know the identity of the deceased?

About doctors sometimes not seeing the cause of death We have been looking for the reason.  Please wait for the fix.

About Guesser, I'll check it when I go back.

**Comment by Tommy-XL** [comment]
3. Detective can't run a meeting through a dead body.

**Comment by KARPED1EM** [comment]
After much checking and testing we did not find any code in the detective that would prevent the report. Check to see if the detective has Oblivious' Subrole. In addition, the dead bodies of lovers who died in love cannot be reported.

**Comment by KARPED1EM** [comment]
Guesser can use other language to guess now
Please wait for new release

**Comment by Tommy-XL** [comment]
I don't include Lovers in the game, probably it was a mistake not related to the Detective
